/**
 * Cloudflare Worker for Discord Webhook
 *
 * This worker receives podcast data and sends it as a formatted embed to a Discord channel.
 *
 * Required secrets (Cloudflare Worker settings -> Variables):
 * - DISCORD_WEBHOOK_URL: The webhook URL for your Discord channel.
 * - WORKER_SECRET: A secret key you define to authenticate requests to this worker.
 */

addEventListener('fetch', (event) => {
  event.respondWith(handleRequest(event.request));
});

async function handleRequest(request) {
  if (request.method !== 'POST') {
    return new Response('Expected POST', { status: 405 });
  }

  // --- Security Check ---
  const authHeader = request.headers.get('Authorization');
  if (!authHeader || authHeader !== `Bearer ${WORKER_SECRET}`) {
    return new Response('Unauthorized', { status: 401 });
  }

  try {
    const podcast = await request.json();

    // --- Prepare Discord Embed ---
    const title = podcast.settings?.topic || 'New Podcast Episode';
    const transcriptSnippet = podcast.transcript ? podcast.transcript.substring(0, 1024) + '...' : 'A new episode is available!';
    const thumbnailUrl = podcast.thumbnailBase64s && podcast.thumbnailBase64s.length > 0 ? podcast.thumbnailBase64s[0] : null;

    const embed = {
      title: title,
      description: transcriptSnippet,
      color: 5814783, // A nice blurple color
      timestamp: new Date(podcast.createdAt).toISOString(),
      footer: {
        text: `Podcast generated by AI Studio`,
      },
    };
    
    if (thumbnailUrl) {
        // Note: Discord webhooks cannot directly use base64 images.
        // For this to work, the image would need to be hosted somewhere publicly accessible.
        // As a fallback, we won't attach the image if it's a data URL.
        // If you host the images, you can change thumbnailUrl to be a real URL.
        if (thumbnailUrl.startsWith('http')) {
            embed.image = { url: thumbnailUrl };
        }
    }

    // The payload for Discord webhook
    const payload = {
      content: `🎙️ **A new podcast episode has been generated!**`,
      embeds: [embed],
    };

    // --- Send to Discord ---
    const response = await fetch(DISCORD_WEBHOOK_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Discord API Error: ${response.status} ${errorText}`);
    }

    return new Response(JSON.stringify({ success: true, message: 'Posted to Discord.' }), {
      headers: { 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Worker Error:', error.message);
    return new Response(JSON.stringify({ success: false, error: error.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}